[package]
name = "aoc_2019"
version = "0.1.0"
authors = ["Leiv Erik"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

voca_rs = "1.9.0"
image = "0.22.3"
num = "0.2.0"
